name: clean_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc_concurrency:
  cached_network_image:
  cupertino_icons:
  dartz:
  dio:
  equatable:
  flutter_bloc:
  flutter_staggered_grid_view:
  flutter_svg:
  formz:
  get_it:
  hive:
  internet_connection_checker:
  intl:
  json_annotation:
  path_provider:
  shimmer:
  stream_transform:
  url_launcher:
  webview_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test:
  build_runner:
  flutter_lints:
  json_serializable:
  change_app_package_name:
  
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/bitmap/
    - assets/images/flags/
    - assets/images/icons/
    - assets/images/illustration/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/icons/CustomIcons.ttf

    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/jakarta/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/jakarta/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/jakarta/PlusJakartaSans-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/jakarta/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/jakarta/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/jakarta/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/jakarta/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/jakarta/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/jakarta/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/jakarta/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/jakarta/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/jakarta/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/jakarta/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/jakarta/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
